metrics:
- accuracy
model_params:
  dense_units: 256
  dropout_rate: 0.4
  freeze_backbone: true
paths:
  labels_ds_path: ''
  subsets_division_ds_path: ''
training_params:
  batch_size: 32
  epochs: 10
  learning_rate: 0.0001
  loss_function: binary_crossentropy
  optimizer: adam
